/**
 * engine-core.ts -- running somebody's ObjectScript against a message.
 *
 * Split out of `engine.ts` so the GUI can do it too. The CLI is a CLI: it reads
 * argv, writes to stderr and calls `process.exit`. None of that can live inside
 * a request handler, and copying the ObjectScript generation into `gui.ts`
 * would be a second implementation of the one thing that must not drift -- the
 * page and the command line have to run the class the same way or a diff
 * between them means nothing.
 *
 * WHY THE MESSAGE IS WRITTEN THROUGH THE SESSION
 *
 * `engine.ts` reads `REMOTE/<basename>`: the message is a file that already
 * exists where the engine can see it. The GUI's message is a TEXTAREA. It may
 * never have been saved, and the point of the pane is to edit it and re-run.
 *
 * So the message goes in the way the scratch class does -- written line by line
 * through the session into `REMOTE`, then imported. That also means the GUI
 * needs no staging step at all, which is the part of `navcheck.ts` that has
 * cost the most time historically.
 */

import { NAMESPACE, REMOTE, runIris, engineLabel } from "./iris-session";

export { engineLabel };

/** An ObjectScript string literal. Quotes double; nothing else is special. */
export function osLiteral(s: string): string {
  return `"${s.split('"').join('""')}"`;
}

/** A line that cannot run outside a production, and the reason in one clause. */
const NEUTRALISE: { re: RegExp; why: string }[] = [
  { re: /SendRequestAsync|SendRequestSync/, why: "dispatch needs a running production" },
  { re: /\$\$\$TRACE/, why: "trace needs a production session" },
];

export function prepareBody(raw: string, firstLine = 1): { body: string; removed: string[] } {
  const removed: string[] = [];
  const body = raw
    .split(/\r?\n/)
    .map((line, i) => {
      const hit = NEUTRALISE.find((n) => n.re.test(line));
      if (!hit) return line;
      removed.push(`line ${firstLine + i}: ${hit.why} -- ${line.trim()}`);
      // Commented rather than dropped, so the line numbers the engine reports
      // in a compile error still match the file on disk.
      return `    // [engine removed] ${line.trim()}`;
    })
    .join("\n");
  return { body, removed };
}

export type Extracted = { body: string; found: string; firstLine: number; error?: string };

/**
 * Take the body out of a whole class file, or hand back what was given.
 *
 * Returns an `error` rather than exiting, because a browser asking for this
 * wants a message in a pane, not a dead server.
 */
export function extractBody(raw: string, method: string): Extracted {
  const empty = { body: "", found: "", firstLine: 1 };

  if (!/^\s*Class\s+[\w.%]+\s+Extends/m.test(raw)) {
    if (/\bExtends\b|\bClassMethod\b|^\s*Method\s/m.test(raw)) {
      const first = raw.split(/\r?\n/).find((l) => l.trim() !== "") ?? "(empty)";
      return {
        ...empty,
        error:
          `This looks like a class file, but no "Class <name> Extends <super>" line ` +
          `could be found in it. The first line reads:\n  ${first.slice(0, 120)}`,
      };
    }
    return { body: raw, found: "a method body", firstLine: 1 };
  }

  const sig = new RegExp(`^\\s*(?:Class)?Method\\s+${method}\\s*\\(`, "m");
  const m = sig.exec(raw);
  if (!m) {
    return { ...empty, error: `No method named "${method}" in this class.` };
  }

  const open = raw.indexOf("{", m.index + m[0].length);
  if (open === -1) return { ...empty, error: `Found ${method} but no body after it.` };

  let depth = 0;
  for (let i = open; i < raw.length; i++) {
    if (raw[i] === "{") depth++;
    else if (raw[i] === "}") {
      depth--;
      if (depth === 0) {
        return {
          body: raw.slice(open + 1, i),
          found: `the body of ${method} in the class file`,
          firstLine: raw.slice(0, open + 1).split(/\r?\n/).length,
        };
      }
    }
  }
  return { ...empty, error: `${method} has an unclosed body.` };
}

/**
 * The scratch class.
 *
 * Extends `Ens.BusinessProcess` so the Ensemble macros a real OnRequest is full
 * of will compile, and exposes the body as a ClassMethod because
 * `Ens.BusinessProcess.%New()` returns "" -- a host is built by a production,
 * not by a caller.
 *
 * The body goes in BARE. A hand-written OnRequest already carries its own
 * `try`, its own `catch` and a closing `quit tsc`, and ObjectScript refuses
 * `QUIT` with an argument inside a TRY block.
 */
export function scratchClass(body: string): string {
  return [
    `Include Ensemble`,
    ``,
    `/// Generated by hl7-bench. Not part of any production.`,
    `Class HL7Bench.Scratch Extends Ens.BusinessProcess [ ClassType = persistent, ProcedureBlock ]`,
    `{`,
    ``,
    `ClassMethod Run(pRequest As EnsLib.HL7.Message, Output tTarget As EnsLib.HL7.Message) As %Status`,
    `{`,
    body,
    `}`,
    ``,
    `Storage Default`,
    `{`,
    `<Type>%Storage.Persistent</Type>`,
    `}`,
    ``,
    `}`,
  ].join("\n");
}

/** Write a text file into the engine, line by line, through the session. */
function writeThrough(remotePath: string, text: string, handle: string): string[] {
  return [
    `set ${handle}=##class(%Stream.FileCharacter).%New()`,
    `set sc=${handle}.LinkToFile("${remotePath}")`,
    ...text.split(/\r\n|\r|\n/).map((l) => `do ${handle}.WriteLine(${osLiteral(l)})`),
    `do ${handle}.%Save()`,
  ];
}

export const SCRATCH_CLS = `${REMOTE}/HL7Bench.Scratch.cls`;
export const SCRATCH_MSG = `${REMOTE}/HL7Bench.Scratch.hl7`;

/**
 * Remove the scratch artifacts. A shared dev server is the normal case, and
 * leaving a class called "Scratch" compiled in one is litter somebody else has
 * to wonder about.
 */
export function cleanupLines(keep = false): string[] {
  return keep
    ? [`write "KEPT|${SCRATCH_CLS} left in place",!`]
    : [
        `do $system.OBJ.Delete("HL7Bench.Scratch","-d")`,
        `do ##class(%File).Delete("${SCRATCH_CLS}")`,
        `do ##class(%File).Delete("${SCRATCH_MSG}")`,
      ];
}

export type RunResult = {
  /** Delivered segments, or null when the code produced no target message. */
  segments: string[] | null;
  removed: string[];
  found: string;
  status: string;
  error?: string;
  engine: string;
};

/**
 * Compile a method body and run one message through it.
 *
 * Both inputs are TEXT, not paths, so the caller may be holding an unsaved
 * editor buffer. Nothing is staged and nothing is left behind.
 */
export function runSource(opts: {
  source: string;
  message: string;
  docType: string;
  method?: string;
  keepScratch?: boolean;
}): RunResult {
  const engine = engineLabel();
  const extracted = extractBody(opts.source, opts.method ?? "OnRequest");
  if (extracted.error) {
    return { segments: null, removed: [], found: "", status: "", error: extracted.error, engine };
  }

  const prepared = prepareBody(extracted.body, extracted.firstLine);
  const cleanup = cleanupLines(opts.keepScratch);

  const script = [
    `zn "${NAMESPACE}"`,
    ...writeThrough(SCRATCH_CLS, scratchClass(prepared.body), "sf"),
    // `$system.Status.IsOK`, never `$$$ISERR`. A piped session has no include
    // file, so a `$$$` macro here is a syntax error the session walks past --
    // which once turned a failed compile into "no target message", a wrong
    // answer that reads like a correct one about a filtered event.
    `set sc=$system.OBJ.Load("${SCRATCH_CLS}","ck-d")`,
    `if '$system.Status.IsOK(sc) { write "ERR|",$system.Status.GetErrorText(sc),! ${cleanup.join(" ")} halt }`,
    `if '##class(%Dictionary.CompiledClass).%ExistsId("HL7Bench.Scratch") { write "ERR|HL7Bench.Scratch did not compile",! ${cleanup.join(" ")} halt }`,
    ...writeThrough(SCRATCH_MSG, opts.message, "mf"),
    `set st=##class(%Stream.FileCharacter).%New(), sc=st.LinkToFile("${SCRATCH_MSG}")`,
    `set src=##class(EnsLib.HL7.Message).ImportFromLibraryStream(st,.sc)`,
    `if '$IsObject($G(src)) { write "ERR|the engine could not read the message back",! ${cleanup.join(" ")} halt }`,
    `do src.PokeDocType("${opts.docType}")`,
    `set tsc = ##class(HL7Bench.Scratch).Run(src,.tgt)`,
    `write "STATUS|",$system.Status.GetErrorText(tsc),!`,
    `if '$IsObject($G(tgt)) { write "NONE|",! ${cleanup.join(" ")} halt }`,
    `for i=1:1:tgt.SegCount { write "OUT|",tgt.GetSegmentAt(i).OutputToString(),! }`,
    ...cleanup,
    `halt`,
  ].join("\n");

  let out: string;
  try {
    out = runIris("engine", script, (o) => /(?:OUT|ERR|NONE|STATUS)\|/.test(o)).out;
  } catch (e) {
    return {
      segments: null,
      removed: prepared.removed,
      found: extracted.found,
      status: "",
      error: e instanceof Error ? e.message : String(e),
      engine,
    };
  }

  // Trailing CR only, never trailing spaces. `irisdb.exe` on Windows echoes a
  // carriage return of its own and the pipe adds CRLF, so a line arrives as
  // "...\r\r\n" and splitting on /\r?\n/ leaves one behind. A trailing SPACE is
  // legal HL7 content and is left exactly where it is.
  const lines = out.split(/\r?\n/).map((l) => l.replace(/\r+$/, ""));
  const marked = (tag: string) =>
    lines.filter((l) => l.startsWith(tag + "|")).map((l) => l.slice(tag.length + 1));

  const err = marked("ERR");
  const base = { removed: prepared.removed, found: extracted.found, engine };
  if (err.length > 0) return { ...base, segments: null, status: "", error: err.join("\n") };

  const status = marked("STATUS")[0] ?? "";
  if (lines.some((l) => l.startsWith("NONE|"))) return { ...base, segments: null, status };

  return { ...base, segments: marked("OUT"), status };
}
