/**
 * hosted.ts -- run a business process class WHOLE, with its dispatch captured.
 *
 * WHY THIS EXISTS
 *
 * `engine.ts --script` normally lifts the body of `OnRequest` into a scratch
 * ClassMethod. That cannot run a class whose `OnRequest` calls an instance
 * method of its own: `..Mapping(...)` from a ClassMethod has no instance to call
 * it on, however the method is copied. It is also exactly the shape an IRIS team
 * writes by hand -- try, `..Mapping`, send -- and the shape `transform: "patch"`
 * emits, so the one gate that proves a class against the goldens could not run
 * the class this tool now recommends.
 *
 * So such a class is compiled whole, under the scratch name, and a subclass
 * overrides `SendRequestAsync` to keep the message instead of queueing it. The
 * subclass is instantiated with a config name -- `%New()` alone dies inside
 * Ens.Host, measured on IRIS for Health 2026.1 -- and the REAL `OnRequest` is
 * called. Nothing in the class is removed or rewritten except its name, so what
 * runs is what will be deployed, `$$$TRACE` lines included (they are no-ops
 * outside a production, not errors).
 *
 * The captured message is the LAST one sent. A class that sends more than once
 * is reported, because only one of its messages is being judged.
 */

/** The scratch host subclass. Deleted with the scratch class after every run. */
export const HOST_CLASS = "HL7Bench.ScratchHost";

/**
 * Instance methods declared in the file that the method under test calls with
 * `..Name(`. Non-empty means the body cannot run lifted, and the class has to
 * run whole.
 */
export function instanceCalls(raw: string, body: string): string[] {
  const declared = new Set<string>();
  for (const m of raw.matchAll(/^\s*Method\s+([\w%]+)\s*\(/gm)) declared.add(m[1]!);
  const called = new Set<string>();
  for (const m of body.matchAll(/\.\.([\w%]+)\s*\(/g)) {
    if (declared.has(m[1]!)) called.add(m[1]!);
  }
  return [...called];
}

/** The class file with its own name replaced by the scratch name. */
export function renamedClass(raw: string, scratch: string): string {
  const re = /^(\s*Class\s+)([\w.%]+)(\s+Extends\b)/m;
  if (!re.test(raw)) throw new Error(`No "Class <name> Extends" line to rename.`);
  return raw.replace(re, `$1${scratch}$3`);
}

/**
 * The capture subclass. The signature has to match Ens.BusinessProcess exactly,
 * `As Ens.Request` included, or the compile refuses the override.
 *
 * The message goes into a %-variable: those are process-wide, so the caller in
 * the session reads it back after `OnRequest` returns, and an object reference
 * cannot live in a global.
 */
export function hostClass(scratch: string): string {
  return [
    `/// Generated by hl7-bench engine.ts. Captures the dispatch; queues nothing.`,
    `Class ${HOST_CLASS} Extends ${scratch}`,
    `{`,
    ``,
    `Method SendRequestAsync(pTargetDispatchName As %String, pRequest As Ens.Request, pResponseRequired As %Boolean = 1, pCompletionKey As %String = "", pDescription As %String = "") As %Status`,
    `{`,
    `  set %HL7BenchSent = pRequest, %HL7BenchSentTo = pTargetDispatchName, %HL7BenchSends = $get(%HL7BenchSends) + 1`,
    `  quit 1`,
    `}`,
    ``,
    `}`,
  ].join("\n");
}

/**
 * The session statements that run one message through the hosted class and
 * leave what it sent in `tgt`, or `tgt` undefined when it sent nothing.
 */
export function hostedCall(src = "src", tgt = "tgt"): string {
  return (
    `kill %HL7BenchSent,%HL7BenchSentTo,%HL7BenchSends,${tgt} ` +
    `set bp=##class(${HOST_CLASS}).%New("${HOST_CLASS}") ` +
    `set tsc=bp.OnRequest(${src},.resp) ` +
    `if $IsObject($get(%HL7BenchSent)) { set ${tgt}=%HL7BenchSent } ` +
    `write "SENT|",$get(%HL7BenchSends,0),"|",$get(%HL7BenchSentTo),!`
  );
}
