// bun test
//
// Style profiles. What matters: the default writes exactly what the house
// backends wrote before styles existed; every preset still emits every
// vocabulary kind; and a style file that says something the tool does not
// understand is refused rather than quietly read as the default.

import { expect, test, describe } from "bun:test";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { emitProcess } from "./emit/process";
import { DEFAULT_STYLE, PRESETS, layout, loadStyle, resolveStyle, type Style } from "./style";
import {
  SOURCE_KINDS, copy, literal, event, lookup, blank, fromFirst, fromWhere, pickRepeat,
  firstOf, todo, sameAs, type Spec, type Source,
} from "./spec";

const patchSpec = (): Spec => ({
  name: "Style Test",
  gate: { path: "MSH-9.2", permit: { A01: "A28" } },
  iris: {
    className: "Style.Test.Dtl",
    sourceDocType: "2.3:ADT_A01",
    targetDocType: "2.3:ADT_A01",
    alwaysPresent: ["PID"],
    process: { className: "Style.Test.Process", sendTo: "ToTarget.ADT.TCP", transform: "patch" },
  },
  blocks: [
    { id: "MSH", wholeSegment: true, rows: [{ target: "MSH-5", from: literal("RECV") }] },
    { id: "PID", wholeSegment: true, rows: [{ target: "PID-19", from: literal("") }] },
    { id: "NK1", wholeSegment: true, repeat: { over: "NK1", skipWhenEmpty: "NK1-2" }, rows: [] },
  ],
});

const mine: Style = resolveStyle({ extends: "lean", indent: "tab", keywords: "Set" });

describe("presets", () => {
  test("no style file means defensive", () => {
    expect(loadStyle(undefined)).toBe(DEFAULT_STYLE);
    expect(DEFAULT_STYLE.name).toBe("defensive");
  });

  test("defensive is exactly what the house backends wrote before styles existed", () => {
    // The class the default emits carries no style name and checks every write.
    const cls = emitProcess(patchSpec(), undefined, PRESETS.defensive);
    expect(cls).toContain("Change the spec and re-emit, not this class.");
    expect(cls).not.toContain(", style ");
    expect(cls).toContain(`$$$ThrowOnError(tRequest.SetValueAt("RECV","MSH:5"))`);
    expect(cls).toContain("$$$ThrowOnError(..Mapping(pRequest,.tRequest,tEvent))");
    expect(cls).toMatch(/Method Mapping[\s\S]*\ttry \{/);
  });

  test("lean leaves ONE check, on the send", () => {
    const cls = emitProcess(patchSpec(), undefined, PRESETS.lean);
    expect(cls.match(/\$\$\$ThrowOnError/g)?.length).toBe(1);
    expect(cls).toContain(`$$$ThrowOnError(..SendRequestAsync("ToTarget.ADT.TCP",tRequest,0))`);
    expect(cls).toContain(`do tRequest.SetValueAt("RECV","MSH:5")`);
    expect(cls).toContain("do ..Mapping(pRequest,.tRequest,tEvent)");
  });

  test("lean's Mapping has no try and returns OK; OnRequest still catches", () => {
    const cls = emitProcess(patchSpec(), undefined, PRESETS.lean);
    const mapping = cls.slice(cls.indexOf("Method Mapping"));
    expect(mapping).not.toContain("try {");
    expect(mapping).toContain("    quit $$$OK");
    expect(cls.slice(0, cls.indexOf("Method Mapping"))).toContain("} catch e {");
  });

  test("lean is neutral: four spaces, lower-case commands", () => {
    const cls = emitProcess(patchSpec(), undefined, PRESETS.lean);
    expect(cls).not.toMatch(/\t/);
    expect(cls).toMatch(/^ {4}set tSC = \$\$\$OK$/m);
    expect(cls).toMatch(/^ {8}if \(tEvent = ""\) \{$/m);
  });

  test("a site file on top of lean: tabs and Set", () => {
    const cls = emitProcess(patchSpec(), undefined, mine);
    expect(cls).toMatch(/^\tSet tSC = \$\$\$OK$/m);
    expect(cls).toMatch(/^\tDo tRequest\.SetValueAt\("RECV","MSH:5"\)$/m);
    expect(cls).toContain(", style lean+local.");
  });
});

describe("the other knobs", () => {
  test("filteredOut: warning, and silent", () => {
    const warn = emitProcess(patchSpec(), undefined, { ...DEFAULT_STYLE, filteredOut: "warning" });
    expect(warn).toContain(`$$$LOGWARNING("Message Filtered Out: MSH-9.2 is "`);
    const quiet = emitProcess(patchSpec(), undefined, { ...DEFAULT_STYLE, filteredOut: "silent" });
    expect(quiet).not.toContain("Message Filtered Out");
    expect(quiet).toContain("Return tSC");
  });

  test("send: unchecked is offered, and writes Do", () => {
    const cls = emitProcess(patchSpec(), undefined, { ...PRESETS.lean!, send: "unchecked" });
    expect(cls).toContain(`do ..SendRequestAsync("ToTarget.ADT.TCP",tRequest,0)`);
    expect(cls).not.toContain("$$$ThrowOnError");
  });

  test("header: none drops the generator line and keeps the description", () => {
    const cls = emitProcess(patchSpec(), undefined, { ...DEFAULT_STYLE, header: "none" });
    expect(cls).not.toContain("Generated by hl7-bench");
    expect(cls.startsWith("/// Business process for Style Test\nClass ")).toBe(true);
  });

  test("comments in the style overrides the spec, and leaves the fingerprint alone", () => {
    const spec = { ...patchSpec(), blocks: [{ ...patchSpec().blocks[0]!, note: "Routing identity" }, ...patchSpec().blocks.slice(1)] };
    const off = emitProcess(spec, undefined, { ...DEFAULT_STYLE, comments: "off" });
    const on = emitProcess(spec, undefined, DEFAULT_STYLE);
    expect(on).toContain("//Routing identity");
    expect(off).not.toContain("//Routing identity");
    const fp = (c: string) => /spec (\w+)/.exec(c)![1];
    expect(fp(off)).toBe(fp(on));
  });
});

describe("layout", () => {
  test("never lower-cases a word inside a string or a comment", () => {
    const text = `\t\tSet x = "If Set Do"\n\t\t//Set this If needed\n\t\tIf (a) Set b = 1`;
    expect(layout({ ...DEFAULT_STYLE, keywords: "set", indent: 2 }, text)).toBe(
      `    set x = "If Set Do"\n    //Set this If needed\n    if (a) set b = 1`,
    );
  });

  test("ElseIf and Else follow a closing brace", () => {
    expect(layout({ ...DEFAULT_STYLE, keywords: "set" }, "\t} ElseIf (x) {\n\t} Else {")).toBe("\t} elseif (x) {\n\t} else {");
  });
});

describe("a style file", () => {
  const dir = mkdtempSync(join(tmpdir(), "style-"));
  const file = (name: string, body: string) => {
    const p = join(dir, name);
    writeFileSync(p, body);
    return p;
  };

  test("is read, and its keys override the preset", () => {
    const s = loadStyle(file("ok.local.json", `{ "extends": "lean", "indent": "tab", "keywords": "Set" }`));
    expect(s).toMatchObject({ writes: "unchecked", mappingTry: false, indent: "tab", keywords: "Set" });
  });

  test("a preset name works in place of a path", () => {
    expect(loadStyle("lean")).toBe(PRESETS.lean);
  });

  test("an unknown key is refused by name, not ignored", () => {
    expect(() => loadStyle(file("typo.local.json", `{ "writ": "unchecked" }`))).toThrow(/"writ" is not a style setting/);
  });

  test("an unknown value is refused, with the choices", () => {
    expect(() => loadStyle(file("bad.local.json", `{ "indent": 3 }`))).toThrow(/Use one of: "tab", 2, 4/);
  });

  test("a missing file is an error, never the default", () => {
    expect(() => loadStyle(join(dir, "nope.json"))).toThrow(/does not exist/);
  });

  test("a BOM from Notepad does not break it", () => {
    expect(loadStyle(file("bom.local.json", `﻿{ "extends": "lean" }`)).writes).toBe("unchecked");
  });
});

describe("every preset emits every kind", () => {
  // Style changes how a line reads, never whether the kind reached the class.
  const samples: Record<(typeof SOURCE_KINDS)[number], Source> = {
    copy: copy("IN1-2"),
    literal: literal("X"),
    firstOf: firstOf("IN1-3", "IN1-2"),
    lookup: lookup("T", "IN1-2", blank()),
    counter: { kind: "counter" },
    event: event(),
    pickRepeat: pickRepeat("IN1-2", 1, "A", 1),
    fromFirst: fromFirst("IN1", "IN1-2", "IN1-3"),
    fromWhere: fromWhere("IN1", "IN1-1", "1", "IN1-2"),
    sameAs: sameAs("MSH-5"),
    todo: todo("later"),
  };
  const styles: Style[] = [PRESETS.defensive!, PRESETS.lean!, mine];
  for (const transform of ["patch", "build"] as const) {
    for (const style of styles) {
      for (const kind of SOURCE_KINDS) {
        test(`${transform} / ${style.name} / ${kind}`, () => {
          const spec: Spec = {
            ...patchSpec(),
            blocks: [
              { id: "MSH", wholeSegment: true, rows: kind === "sameAs" ? [{ target: "MSH-5", from: literal("R") }] : [] },
              { id: "IN1", wholeSegment: true, repeat: { over: "IN1" }, rows: [{ target: "IN1-4", from: samples[kind] }] },
            ],
          };
          spec.iris.process = { ...spec.iris.process!, transform };
          const cls = emitProcess(spec, undefined, style);
          const body = cls.slice(cls.indexOf("Method Mapping"));
          if (kind === "todo") expect(body).toMatch(/TODO IN1-4/);
          else expect(body).toMatch(/SetValueAt\([^\n]*IN1\(|SetValueAt\([^\n]*"IN1/);
          expect(body).not.toMatch(/\{[A-Z0-9]{3}[:(]/);
        });
      }
    }
  }
});
