// bun test
//
// Two things are being protected here.
//
// The first is ObjectScript that compiles. There is no IRIS on this machine, so
// the checks are the syntax rules the emitter could break silently: a `{PID:3}`
// brace in a Method body is a DTL feature and a syntax error here, and a free
// text spec field with a quote in it closes a string literal early.
//
// The second is the HEADER, which is not decoration. The DTL says "proven on
// the bench" and has earned it. This file has executed nothing, and if it
// carried the same banner the DTL's banner would stop meaning anything.

import { expect, test, describe } from "bun:test";

import { emitProcess } from "./process";
import { type Spec } from "../spec";

const base = (over: Partial<Spec["iris"]> = {}, gate?: Spec["gate"]): Spec => ({
  name: "Process Emit Test",
  gate: gate ?? { path: "MSH-9.2", permit: { A01: "A01", A08: "A08" } },
  iris: {
    className: "Site.Interface.DTL.Thing",
    sourceDocType: "2.3:ADT_A01",
    targetDocType: "2.3:ADT_A01",
    process: { className: "Site.Interface.Process.Thing", sendTo: "ToTarget.ADT.TCP" },
    ...over,
  },
  blocks: [],
});

describe("the one fact the bench cannot derive", () => {
  test("no iris.process is a refusal that shows the shape to add", () => {
    const spec = base();
    delete spec.iris.process;
    expect(() => emitProcess(spec)).toThrow(/iris.process/);
    expect(() => emitProcess(spec)).toThrow(/sendTo/);
  });
});

describe("header", () => {
  const cls = emitProcess(base());

  test("says TEMPLATE", () => {
    expect(cls).toContain("TEMPLATE generated by hl7-bench");
  });

  // The DTL's banner is the one line in that file that has to be believed, and
  // it only stays believable while this file does not copy it.
  test("does not claim to be proven on the bench", () => {
    expect(cls).not.toContain("proven on the bench.");
    expect(cls).toContain("NOT proven on the bench");
  });

  test("names which shop pattern it models rather than implying it is the pattern", () => {
    expect(cls).toContain("one shop's shape");
    expect(cls).toContain("routing engine");
  });

  test("carries the same fingerprint the DTL carries", () => {
    expect(cls).toMatch(/Spec fingerprint: [0-9a-f]{12}/);
  });

  test("names the config item and says the failure is at run time", () => {
    expect(cls).toContain("ToTarget.ADT.TCP");
    expect(cls).toContain("fails at RUN time");
  });

  test("Include Ensemble comes first, or the macros do not resolve", () => {
    expect(cls).toStartWith("Include Ensemble");
  });
});

describe("the class", () => {
  test("extends Ens.BusinessProcess as a persistent procedure block", () => {
    expect(emitProcess(base())).toContain(
      "Class Site.Interface.Process.Thing Extends Ens.BusinessProcess [ ClassType = persistent, ProcedureBlock ]",
    );
  });

  test("the transform is called by class name and its status is checked", () => {
    const cls = emitProcess(base());
    expect(cls).toContain("##class(Site.Interface.DTL.Thing).Transform(tSource, .tTarget)");
    expect(cls).toContain("if $$$ISERR(tSC) quit tSC");
  });

  test("with no DTL class name the call is commented out, not invented", () => {
    const spec = base();
    delete spec.iris.className;
    const cls = emitProcess(spec);
    expect(cls).toContain("// set tSC = ##class(Your.Transform.Class)");
    expect(cls).not.toMatch(/^\s+set tSC = ##class/m);
  });

  test("the request is cloned before anything touches it", () => {
    const cls = emitProcess(base());
    expect(cls).toContain("set tSource = pRequest.%ConstructClone(1)");
    // Cloned, then transformed FROM the clone. Transforming from pRequest with
    // a clone sitting unused would look right and do nothing.
    expect(cls.indexOf("%ConstructClone")).toBeLessThan(cls.indexOf(".Transform("));
  });

  test("create='copy' says the clone is load-bearing rather than cautious", () => {
    expect(emitProcess(base({ create: "copy" }))).toContain("load-bearing");
    expect(emitProcess(base({ create: "new" }))).toContain("Clone anyway");
  });

  test("dispatch is fire and forget, and the 0 is explained", () => {
    const cls = emitProcess(base());
    expect(cls).toContain(`..SendRequestAsync("ToTarget.ADT.TCP", tTarget, 0)`);
    expect(cls).toContain("pResponseRequired");
  });
});

describe("the gate", () => {
  test("a refused event returns success with a trace, never an error", () => {
    const cls = emitProcess(base());
    const filter = cls.slice(cls.indexOf("set tEvent"), cls.indexOf("%ConstructClone"));
    expect(filter).toContain("$$$TRACE(");
    expect(filter).toContain("quit $$$OK");
    expect(filter).not.toContain("$$$ERROR");
  });

  test("several triggers become an AND chain of not-equals", () => {
    expect(emitProcess(base())).toContain(`if (tEvent '= "A01") && (tEvent '= "A08") {`);
  });

  test("one trigger does not get pointless parentheses", () => {
    const one = base({}, { path: "MSH-9.2", permit: { A01: "A01" } });
    expect(emitProcess(one)).toContain(`if tEvent '= "A01" {`);
  });

  test("the event field is read once into a variable, not three times", () => {
    const cls = emitProcess(base());
    expect(cls.match(/GetValueAt\("MSH:9\.2"\)/g)).toHaveLength(1);
  });

  test("gate.require becomes its own refusal, also returning success", () => {
    const spec = base({}, {
      path: "MSH-9.2",
      permit: { A01: "A01" },
      require: [{ path: "MSH-9.1", equals: "ADT" }],
    });
    const cls = emitProcess(spec);
    expect(cls).toContain(`if pRequest.GetValueAt("MSH:9.1") '= "ADT" {`);
    expect(cls).toContain("quit $$$OK");
  });
});

describe("ObjectScript that has to compile", () => {
  // The DTL curly form is a compiler feature of a DTL attribute. In a Method
  // body it is a syntax error, and the error names the expression rather than
  // the file that produced it.
  test("no braced path anywhere in the method body", () => {
    const cls = emitProcess(base());
    expect(cls).not.toMatch(/\{[A-Z0-9]{3}[:(]/);
  });

  test("a quote in a config item name doubles instead of closing the string", () => {
    const spec = base({ process: { className: "A.B", sendTo: `To"Weird".TCP` } });
    const cls = emitProcess(spec);
    expect(cls).toContain(`..SendRequestAsync("To""Weird"".TCP", tTarget, 0)`);
  });

  test("a comment with a newline in it stays on one /// line", () => {
    const spec = base({
      process: { className: "A.B", sendTo: "X", comment: "one\ntwo" },
    });
    const lines = emitProcess(spec).split("\n");
    expect(lines.filter((l) => l.includes("one two"))).toHaveLength(1);
    expect(lines.some((l) => l.trim() === "two")).toBe(false);
  });
});
