// bun test
//
// Two things are being protected here.
//
// The first is ObjectScript that compiles. There is no IRIS on this machine, so
// the checks are the syntax rules the emitter could break silently: a `{PID:3}`
// brace in a Method body is a DTL feature and a syntax error here, and a free
// text spec field with a quote in it closes a string literal early.
//
// The second is the HEADER, which is not decoration. The DTL says "proven on
// the bench" and has earned it. This file has executed nothing, and if it
// carried the same banner the DTL's banner would stop meaning anything.

import { expect, test, describe } from "bun:test";

import { emitProcess } from "./process";
import { blank, literal, lookup, type Spec } from "../spec";

const base = (over: Partial<Spec["iris"]> = {}, gate?: Spec["gate"]): Spec => ({
  name: "Process Emit Test",
  gate: gate ?? { path: "MSH-9.2", permit: { A01: "A01", A08: "A08" } },
  iris: {
    className: "Site.Interface.DTL.Thing",
    sourceDocType: "2.3:ADT_A01",
    targetDocType: "2.3:ADT_A01",
    process: { className: "Site.Interface.Process.Thing", sendTo: "ToTarget.ADT.TCP" },
    ...over,
  },
  blocks: [],
});

describe("the one fact the bench cannot derive", () => {
  test("no iris.process is a refusal that shows the shape to add", () => {
    const spec = base();
    delete spec.iris.process;
    expect(() => emitProcess(spec)).toThrow(/iris.process/);
    expect(() => emitProcess(spec)).toThrow(/sendTo/);
  });
});

describe("header", () => {
  const cls = emitProcess(base());

  test("says TEMPLATE", () => {
    expect(cls).toContain("TEMPLATE generated by hl7-bench");
  });

  // The DTL's banner is the one line in that file that has to be believed, and
  // it only stays believable while this file does not copy it.
  test("does not claim to be proven on the bench", () => {
    expect(cls).not.toContain("proven on the bench.");
    expect(cls).toContain("NOT proven on the bench");
  });

  // This prose is the essay `iris.comments` exists to cut: it is about this
  // TOOL's opinion of process shapes, not about the interface, and the
  // receiving site maintains the class. It still has to be RIGHT where it is
  // still printed, so the assertion moved to a spec that asks for it rather
  // than being deleted or loosened to pass at both levels.
  test("at full, names which shop pattern it models rather than implying it is the pattern", () => {
    const full = emitProcess(base({ comments: "full" }));
    expect(full).toContain("one shop's shape");
    expect(full).toContain("routing engine");
  });

  test("at brief, the shop-pattern essay is gone", () => {
    expect(cls).not.toContain("one shop's shape");
  });

  test("carries the same fingerprint the DTL carries", () => {
    expect(cls).toMatch(/Spec fingerprint: [0-9a-f]{12}/);
  });

  test("names the config item and says the failure is at run time", () => {
    expect(cls).toContain("ToTarget.ADT.TCP");
    expect(cls).toContain("fails at RUN time");
  });

  test("Include Ensemble comes first, or the macros do not resolve", () => {
    expect(cls).toStartWith("Include Ensemble");
  });
});

describe("the class", () => {
  test("extends Ens.BusinessProcess as a persistent procedure block", () => {
    expect(emitProcess(base())).toContain(
      "Class Site.Interface.Process.Thing Extends Ens.BusinessProcess [ ClassType = persistent, ProcedureBlock ]",
    );
  });

  test("the transform is called by class name and its status is checked", () => {
    const cls = emitProcess(base());
    expect(cls).toContain("##class(Site.Interface.DTL.Thing).Transform(tSource, .tTarget)");
    expect(cls).toContain("if $$$ISERR(tSC) quit tSC");
  });

  test("with no DTL class name the call is commented out, not invented", () => {
    const spec = base();
    delete spec.iris.className;
    const cls = emitProcess(spec);
    expect(cls).toContain("// set tSC = ##class(Your.Transform.Class)");
    expect(cls).not.toMatch(/^\s+set tSC = ##class/m);
  });

  test("the request is cloned before anything touches it", () => {
    const cls = emitProcess(base());
    expect(cls).toContain("set tSource = pRequest.%ConstructClone(1)");
    // Cloned, then transformed FROM the clone. Transforming from pRequest with
    // a clone sitting unused would look right and do nothing.
    expect(cls.indexOf("%ConstructClone")).toBeLessThan(cls.indexOf(".Transform("));
  });

  test("create='copy' says the clone is load-bearing rather than cautious", () => {
    expect(emitProcess(base({ create: "copy" }))).toContain("load-bearing");
    expect(emitProcess(base({ create: "new" }))).toContain("Clone anyway");
  });

  test("dispatch is fire and forget, and the 0 is explained", () => {
    const cls = emitProcess(base());
    expect(cls).toContain(`..SendRequestAsync("ToTarget.ADT.TCP", tTarget, 0)`);
    expect(cls).toContain("pResponseRequired");
  });
});

describe("the gate", () => {
  test("a refused event returns success with a trace, never an error", () => {
    const cls = emitProcess(base());
    const filter = cls.slice(cls.indexOf("set tEvent"), cls.indexOf("%ConstructClone"));
    expect(filter).toContain("$$$TRACE(");
    expect(filter).toContain("quit $$$OK");
    expect(filter).not.toContain("$$$ERROR");
  });

  test("several triggers become an AND chain of not-equals", () => {
    expect(emitProcess(base())).toContain(`if (tEvent '= "A01") && (tEvent '= "A08") {`);
  });

  test("one trigger does not get pointless parentheses", () => {
    const one = base({}, { path: "MSH-9.2", permit: { A01: "A01" } });
    expect(emitProcess(one)).toContain(`if tEvent '= "A01" {`);
  });

  test("the event field is read once into a variable, not three times", () => {
    const cls = emitProcess(base());
    expect(cls.match(/GetValueAt\("MSH:9\.2"\)/g)).toHaveLength(1);
  });

  test("gate.require becomes its own refusal, also returning success", () => {
    const spec = base({}, {
      path: "MSH-9.2",
      permit: { A01: "A01" },
      require: [{ path: "MSH-9.1", equals: "ADT" }],
    });
    const cls = emitProcess(spec);
    expect(cls).toContain(`if pRequest.GetValueAt("MSH:9.1") '= "ADT" {`);
    expect(cls).toContain("quit $$$OK");
  });
});

describe("ObjectScript that has to compile", () => {
  // The DTL curly form is a compiler feature of a DTL attribute. In a Method
  // body it is a syntax error, and the error names the expression rather than
  // the file that produced it.
  test("no braced path anywhere in the method body", () => {
    const cls = emitProcess(base());
    expect(cls).not.toMatch(/\{[A-Z0-9]{3}[:(]/);
  });

  test("a quote in a config item name doubles instead of closing the string", () => {
    const spec = base({ process: { className: "A.B", sendTo: `To"Weird".TCP` } });
    const cls = emitProcess(spec);
    expect(cls).toContain(`..SendRequestAsync("To""Weird"".TCP", tTarget, 0)`);
  });

  test("a comment with a newline in it stays on one /// line", () => {
    const spec = base({
      process: { className: "A.B", sendTo: "X", comment: "one\ntwo" },
    });
    const lines = emitProcess(spec).split("\n");
    expect(lines.filter((l) => l.includes("one two"))).toHaveLength(1);
    expect(lines.some((l) => l.trim() === "two")).toBe(false);
  });
});

describe("stamps", () => {
  const withStamp = (stamp: NonNullable<Spec["iris"]["process"]>["stamp"]) =>
    emitProcess(
      base({
        process: {
          className: "Site.Interface.Process.Thing",
          sendTo: "ToTarget.ADT.TCP",
          stamp,
        },
      }),
    );

  test("no stamp array emits no SetValueAt and no IsMutable", () => {
    const cls = emitProcess(base());
    expect(cls).not.toContain("SetValueAt");
    expect(cls).not.toContain("IsMutable");
  });

  test("an empty stamp array is the same as none", () => {
    expect(withStamp([])).not.toContain("IsMutable");
  });

  test("a stamp becomes a SetValueAt with the colon path form", () => {
    const cls = withStamp([{ path: "MSH-4", value: "WEST_LAB", why: "receiver routes on facility" }]);
    expect(cls).toContain(`do tTarget.SetValueAt("WEST_LAB", "MSH:4")`);
  });

  // The whole point of the feature. Without this line the class compiles and
  // then fails once per message, at run time, in a namespace.
  test("IsMutable is set once, before the first write", () => {
    const cls = withStamp([
      { path: "MSH-4", value: "A", why: "one" },
      { path: "MSH-6", value: "B", why: "two" },
    ]);
    expect(cls.match(/set tTarget\.IsMutable = 1/g)).toHaveLength(1);
    expect(cls.indexOf("IsMutable")).toBeLessThan(cls.indexOf("SetValueAt"));
  });

  test("stamps land after the transform and before the dispatch", () => {
    const cls = withStamp([{ path: "MSH-4", value: "A", why: "one" }]);
    expect(cls.indexOf(").Transform(")).toBeLessThan(cls.indexOf("SetValueAt"));
    expect(cls.indexOf("SetValueAt")).toBeLessThan(cls.indexOf("SendRequestAsync"));
  });

  test("each why is carried into the body as a comment", () => {
    const cls = withStamp([{ path: "MSH-4", value: "A", why: "two receivers, two facility codes" }]);
    expect(cls).toContain("    // two receivers, two facility codes");
  });

  test("the header lists the stamps and warns the trace does not cover them", () => {
    const cls = withStamp([{ path: "MSH-4", value: "WEST_LAB", why: "receiver routes on facility" }]);
    expect(cls).toContain(`///   MSH-4 = "WEST_LAB" -- receiver routes on facility`);
    expect(cls).toContain("NOT in the DTL");
  });

  test("a quote in a stamp value doubles instead of closing the string", () => {
    const cls = withStamp([{ path: "MSH-4", value: `A"B`, why: "quoting" }]);
    expect(cls).toContain(`do tTarget.SetValueAt("A""B", "MSH:4")`);
  });

  test("a newline in a why stays on one comment line", () => {
    const cls = withStamp([{ path: "MSH-4", value: "A", why: "one\ntwo" }]);
    expect(cls).toContain("    // one two");
    expect(cls.split("\n").some((l) => l.trim() === "two")).toBe(false);
  });

  test("no braced path sneaks in through a stamp", () => {
    const cls = withStamp([{ path: "MSH-4", value: "A", why: "one" }]);
    expect(cls).not.toMatch(/\{[A-Z0-9]{3}[:(]/);
  });
});

// ---------------------------------------------------------------------------
// iris.process.transform: "inline"
//
// The self-contained shape. A receiving team that will not deploy a DTL is a
// real constraint, and the interface has to fit in the one class they accept.
//
// Two things are protected here. The first is the same one the top of this
// file names: ObjectScript that compiles, which for this backend means no
// braced path anywhere in a Method body. The second is that the class is
// actually SELF-CONTAINED -- a process that still calls a DTL while claiming
// to be inline compiles perfectly and dies at run time naming a transform
// nobody agreed to ship.
// ---------------------------------------------------------------------------

describe("the inline mapping", () => {
  const inlineSpec = (blocks: Spec["blocks"] = []): Spec => {
    const spec = base();
    spec.iris.process!.transform = "inline";
    spec.blocks = blocks;
    return spec;
  };

  const seeded = (): Spec =>
    inlineSpec([
      { id: "PID", wholeSegment: true, rows: [{ target: "PID-19", from: literal("") }] },
      { id: "NK1", wholeSegment: true, repeat: { over: "NK1", skipWhenEmpty: "NK1-2" }, rows: [] },
    ]);

  /** The class from `Method OnRequest` down, which is where braces are fatal. */
  const body = (spec: Spec): string => {
    const cls = emitProcess(spec);
    const at = cls.indexOf("Method OnRequest");
    expect(at).toBeGreaterThan(-1);
    return cls.slice(at);
  };

  test("calls no transform class, which is the whole point", () => {
    expect(body(seeded())).not.toContain(".Transform(");
  });

  test("the default is still dtl, so an existing spec is untouched", () => {
    const spec = seeded();
    delete spec.iris.process!.transform;
    expect(body(spec)).toContain(".Transform(tSource, .tTarget)");
  });

  test("transform: dtl said out loud is the same class as saying nothing", () => {
    const explicit = seeded();
    explicit.iris.process!.transform = "dtl";
    const implicit = seeded();
    delete implicit.iris.process!.transform;
    // Not the whole class: the fingerprint covers the spec, and these two
    // specs differ by a key. The BODY is what has to be identical.
    expect(body(explicit)).toBe(body(implicit));
  });

  // The failure this backend exists to avoid making. A brace is a DTL compiler
  // feature; in a Method body it is "invalid name" at compile time, and it
  // reads as a perfectly ordinary path right up until then.
  test("no braced path reaches the Method body", () => {
    expect(body(seeded())).not.toMatch(/\{[A-Z0-9]{3}[:(]/);
  });

  test("a whole-segment block becomes one SetValueAt of segment to segment", () => {
    expect(body(seeded())).toContain(`..ValueAt(tSource,"PID")`);
    expect(body(seeded())).toContain(`tTarget.SetValueAt(tSeed, "PID")`);
  });

  // GetValueAt on a path whose segment is absent THROWS, and an unhandled
  // throw kills the business process. A message with no PV2 is ordinary.
  test("every read is guarded, so an absent optional segment cannot throw", () => {
    const b = body(seeded());
    expect(b).toContain("ClassMethod ValueAt(");
    expect(b).toContain("try {");
    expect(b).toContain("} catch {");
    // No bare read of the inbound document survives anywhere in the body.
    expect(b).not.toMatch(/tSource\.GetValueAt\(/);
    expect(b).not.toMatch(/pRequest\.GetValueAt\(/);
  });

  test("the guarded read is not emitted when nothing calls it", () => {
    const spec = seeded();
    delete spec.iris.process!.transform;
    expect(emitProcess(spec)).not.toContain("ClassMethod ValueAt(");
  });

  // An absent repeating segment reads as "" and + makes that 0, so the loop
  // runs no times. Without the +, "" as a FOR bound is a different failure.
  test("a repeat counts occurrences once, numerically, before looping", () => {
    const b = body(seeded());
    expect(b).toContain(`set cnt1 = +..ValueAt(tSource, "NK1(*)")`);
    expect(b).toContain("for k1=1:1:cnt1 {");
  });

  test("a repeat numbers the target by output ordinal, not by source repeat", () => {
    const b = body(seeded());
    expect(b).toContain(`..ValueAt(tSource,"NK1("_k1_")")`);
    expect(b).toContain(`tTarget.SetValueAt(tSeed, "NK1("_n1_")")`);
  });

  test("the target is built and told its DocType, or nothing resolves", () => {
    const b = body(seeded());
    expect(b).toContain("##class(EnsLib.HL7.Message).%New()");
    expect(b).toContain(`PokeDocType("2.3:ADT_A01")`);
    // Immutable is set before the mapping WRITES, not only before the stamps:
    // inline fills the target itself, so the stamps block is far too late.
    // Measured against a real write statement rather than the word, which also
    // appears in the comment explaining why the line is there.
    expect(b.indexOf("set tTarget.IsMutable = 1"))
      .toBeLessThan(b.indexOf("set tWriteSC = tTarget.SetValueAt("));
  });

  test("a lookup calls the function set, because ..Lookup is a DTL method", () => {
    const spec = inlineSpec([
      { id: "PID", rows: [{ target: "PID-8", from: lookup("Sex", "PID-8", blank()) }] },
    ]);
    spec.tables = { Sex: { M: "1" } };
    const b = body(spec);
    expect(b).toContain("##class(Ens.Util.FunctionSet).Lookup(");
    // `..Lookup` exists on Ens.DataTransformDTL and nowhere else, so it must
    // not survive into a business process.
    expect(b).not.toMatch(/[^.]\.\.Lookup\(/);
  });

  test("the header says self-contained rather than naming a DTL it does not call", () => {
    const cls = emitProcess(seeded());
    expect(cls).toContain("SELF-CONTAINED");
    expect(cls).not.toContain("/// Calls: Site.Interface.DTL.Thing");
  });

  test("it still says TEMPLATE, because nothing here has been executed either", () => {
    expect(emitProcess(seeded())).toContain("NOT proven on the bench");
  });

  test("the gate, the clone, the stamp block and the dispatch all survive", () => {
    const spec = seeded();
    spec.iris.process!.stamp = [{ path: "MSH-4", value: "W", why: "receiver routes on it" }];
    const b = body(spec);
    expect(b).toContain(`set tEvent = ..ValueAt(pRequest, "MSH:9.2")`);
    expect(b).toContain("set tSource = pRequest.%ConstructClone(1)");
    expect(b).toContain("set tTarget.IsMutable = 1");
    expect(b).toContain(`do tTarget.SetValueAt("W", "MSH:4")`);
    expect(b).toContain(`..SendRequestAsync("ToTarget.ADT.TCP", tTarget, 0)`);
  });
});
