/**
 * emit/process.ts -- a spec becomes an Ens.BusinessProcess TEMPLATE.
 *
 * WHY THIS FILE SAYS TEMPLATE AND emit/iris.ts DOES NOT
 *
 * The DTL header says *proven on the bench* and it is entitled to: real messages
 * went through that mapping, on this machine, and you read the output. There is
 * nothing here to run. `OnRequest` takes a request object out of a running
 * production and hands it to a queue, and none of that exists on a laptop. So
 * this is a starting point that compiles, and the file says so in its first
 * line. If both artifacts carried the same confident banner, the DTL's banner
 * would stop meaning anything, and that banner is the one line in that file that
 * has to be believed.
 *
 * ONE SHOP'S PATTERN, NOT THE PATTERN
 *
 * What comes out is a custom business process that clones the request, calls a
 * DTL, and dispatches by config item name with SendRequestAsync. That is a
 * common and perfectly good shape, and it is not the only one. Plenty of sites
 * use EnsLib.HL7.MsgRouter.RoutingEngine with a rule whose transform field names
 * the DTL, and never write a process class at all. If your production already
 * has a routing engine in front of this transform, you probably do not want this
 * file. Read it, take the parts you need.
 *
 * THE GATE IS NOW IN TWO PLACES, AND THAT IS A DECISION
 *
 * `emit/iris.ts` prints a routing rule condition. The class below filters on the
 * same gate. Those are two ways of saying one thing, and you want one of them:
 *
 *   - Routing engine in front? The rule holds the gate. The filter below is
 *     redundant, harmless, and worth keeping as a belt if you like.
 *   - This process wired straight to the service? The filter below IS the gate.
 *     Delete it and every message the sender emits reaches the transform.
 *
 * Emitting it in both places is deliberate. A gate that exists in neither is the
 * failure that matters, and it is silent.
 */

import { os } from "./iris";
import { fingerprint } from "../fingerprint";
import type { Spec } from "../spec";

// ---------------------------------------------------------------------------

/**
 * Bench path to the string `GetValueAt` wants. "MSH-9.2" becomes "MSH:9.2".
 *
 * Deliberately not `dtlPath`: the curly form is a DTL compiler feature and this
 * file is plain ObjectScript in a Method body, where a brace is a syntax error
 * rather than a path.
 */
function ref(obj: string, path: string): string {
  return `${obj}.GetValueAt(${os(path.replace("-", ":"))})`;
}

/** Comment text that cannot end a `///` line early or open a block comment. */
function comment(s: string): string {
  return s.replace(/\r?\n/g, " ").replace(/\*\//g, "* /");
}

// ---------------------------------------------------------------------------

/**
 * The business process class. Throws when `spec.iris.process` is absent, because
 * there is no sensible default for the one fact it carries that nothing else in
 * the spec does: the name of the config item to dispatch to.
 */
export function emitProcess(spec: Spec): string {
  const proc = spec.iris.process;
  if (!proc) {
    throw new Error(
      `This spec has no iris.process. Add it to emit a business process:\n` +
        `  iris: { process: { className: "Site.Interface.Process.X", sendTo: "ToTarget.ADT.TCP" } }\n` +
        `sendTo is the config item name as it is spelled in the production, and it is the ` +
        `one fact the bench cannot work out for itself.`,
    );
  }

  const dtl = spec.iris.className;
  const triggers = Object.keys(spec.gate.permit);
  const requires = spec.gate.require ?? [];
  const out: string[] = [];

  // $$$TRACE and $$$ISERR are Ensemble macros. Without this line the class does
  // not compile, and the error names the macro rather than the missing include.
  out.push(`Include Ensemble`, ``);

  out.push(
    `/// ${comment(proc.comment ?? `Business process for ${spec.name}`)}`,
    `///`,
    `/// Spec fingerprint: ${fingerprint(spec)}`,
    `///   The same string the DTL carries. Two classes out of one spec, and this`,
    `///   is how you tell whether they are still the same one.`,
    `///`,
    `/// TEMPLATE generated by hl7-bench. NOT proven on the bench: there is no`,
    `/// production on a laptop and nothing here has been executed. The DTL this`,
    `/// calls was proven; this file is a starting point that compiles.`,
    `///`,
    `/// The pattern below is a custom business process that clones the request,`,
    `/// calls a DTL, and dispatches by config item name. It is one shop's shape,`,
    `/// not the only one. A routing engine with a rule whose transform field names`,
    `/// the DTL does the same work with no class at all.`,
    `///`,
    `/// Before this does anything in a namespace:`,
    `///   1. Add it to the production as a Business Process.`,
    `///   2. Confirm "${comment(proc.sendTo)}" is spelled exactly as the config item is.`,
    `///      A name that does not resolve fails at RUN time, per message, not at`,
    `///      compile time.`,
    `///   3. Decide where the gate lives. If a routing rule already filters these`,
    `///      messages, the filter below is a second copy of it.`,
  );

  if (dtl) out.push(`///`, `/// Calls: ${comment(dtl)}`);
  out.push(
    `///`,
    `/// Handles: ${triggers.join(", ")} from ${spec.gate.path}`,
    ``,
    `Class ${proc.className} Extends Ens.BusinessProcess [ ClassType = persistent, ProcedureBlock ]`,
    `{`,
    ``,
    `Method OnRequest(pRequest As EnsLib.HL7.Message, Output pResponse As Ens.Response) As %Status`,
    `{`,
    `    #dim tSC As %Status = $$$OK`,
    `    #dim tEvent As %String`,
    `    #dim tSource As EnsLib.HL7.Message`,
    `    #dim tTarget As EnsLib.HL7.Message`,
    ``,
  );

  // ---- trigger event filter -------------------------------------------------
  const eventRef = ref("pRequest", spec.gate.path);
  out.push(
    `    // The events this interface handles. Anything else returns SUCCESS with a`,
    `    // trace, deliberately, and never an error. A message this interface is not`,
    `    // for is a correct outcome, and an error queue full of correct outcomes`,
    `    // teaches everyone to stop reading the error queue.`,
    `    set tEvent = ${eventRef}`,
  );
  if (triggers.length === 1) {
    out.push(`    if tEvent '= ${os(triggers[0])} {`);
  } else {
    const arms = triggers.map((t) => `(tEvent '= ${os(t)})`).join(" && ");
    out.push(`    if ${arms} {`);
  }
  out.push(
    `        $$$TRACE(${os(`${spec.gate.path} is `)}_tEvent_${os(`, which this interface does not handle`)})`,
    `        quit $$$OK`,
    `    }`,
    ``,
  );

  // ---- required equalities --------------------------------------------------
  if (requires.length > 0) {
    out.push(
      `    // Everything else the gate requires. Same rule: refused, not failed.`,
      `    // A feed that puts an A08 in ${spec.gate.path} while ${requires[0].path} says`,
      `    // something else is real, and the receiver believes one of them.`,
    );
    for (const r of requires) {
      out.push(
        `    if ${ref("pRequest", r.path)} '= ${os(r.equals)} {`,
        `        $$$TRACE(${os(`${r.path} is not `)}_${os(r.equals)}_${os(`, refusing`)})`,
        `        quit $$$OK`,
        `    }`,
      );
    }
    out.push(``);
  }

  // ---- clone ----------------------------------------------------------------
  const create = spec.iris.create ?? "new";
  out.push(
    `    // The request object is shared with every other target the router handed`,
    `    // this message to. Anything written to it is written to THEIR copy as well,`,
    create === "copy"
      ? `    // and create='copy' means the transform starts from this object, so the`
        + `\n    // clone here is load-bearing rather than cautious.`
      : `    // and while create='new' builds a fresh target and touches nothing, that`
        + `\n    // is a property of today's spec and not of this class. Clone anyway.`,
    `    set tSource = pRequest.%ConstructClone(1)`,
    ``,
  );

  // ---- transform ------------------------------------------------------------
  if (dtl) {
    out.push(
      `    set tSC = ##class(${dtl}).Transform(tSource, .tTarget)`,
      `    if $$$ISERR(tSC) quit tSC`,
      ``,
    );
  } else {
    out.push(
      `    // iris.className is not set in the spec, so the transform class cannot be`,
      `    // named here. Set it and regenerate rather than typing a name in: a name`,
      `    // typed here is a name the spec does not know about.`,
      `    // set tSC = ##class(Your.Transform.Class).Transform(tSource, .tTarget)`,
      `    // if $$$ISERR(tSC) quit tSC`,
      ``,
    );
  }

  // ---- dispatch -------------------------------------------------------------
  out.push(
    `    // The 0 is pResponseRequired. Fire and forget: no OnResponse method, no`,
    `    // reply correlated back to this process. An ACK from the receiving`,
    `    // operation is handled by the operation, not here. Pass 1 instead and this`,
    `    // class needs an OnResponse or it will sit waiting.`,
    `    set tSC = ..SendRequestAsync(${os(proc.sendTo)}, tTarget, 0)`,
    ``,
    `    quit tSC`,
    `}`,
    ``,
    `}`,
    ``,
  );

  return out.join("\n");
}
