/**
 * emit/schema.ts -- the custom schema category, as an IRIS import document.
 *
 * A DTL walks the SCHEMA. A DocType naming a category IRIS does not have is not
 * an error at compile time and not an error at run time: the structure walk
 * finds nothing, every named path resolves to empty, and the transform delivers
 * a well-formed message with nothing in it.
 *
 * So the category is an artifact this spec SHIPS, next to the class and the
 * lookup tables, rather than a step in somebody's head.
 *
 *   bun emit.ts schema > exa-schema.xml
 *   do ##class(EnsLib.HL7.SchemaXML).Import("/lab/exa-schema.xml", .cat)
 *
 * In a production the category is then named in the HL7 Business Service's
 * MessageSchemaCategory setting. Nothing in a message names it -- MSH-12 is the
 * HL7 VERSION, not the schema CATEGORY, so anything deriving the DocType from
 * MSH-12 alone lands on the stock category and fails silently.
 */

import type { CustomSchema, Spec } from "../spec";

/** Escape for XML character data and attribute values. */
function x(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Escape for an XML COMMENT, where the rule is different and surprising.
 *
 * "--" is illegal inside a comment, full stop, and the SAX parser rejects the
 * whole document for it. That includes a "--" used as ordinary punctuation in a
 * sentence, which is how this was found.
 */
function comment(s: string): string {
  return s.replace(/--+/g, "-");
}

export function emitSchema(spec: Spec): string {
  const sch: CustomSchema | undefined = spec.iris.schema;
  if (!sch) {
    throw new Error(
      `Spec "${spec.name}" declares no iris.schema, so there is no category to emit.`,
    );
  }

  const out: string[] = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!--`,
    `  ${comment(sch.category)} : generated by hl7-bench from the spec "${comment(spec.name)}".`,
    `  Do not hand-edit. Change iris.schema in transform.ts and emit again.`,
    ``,
    `  This category is a DEPENDENCY of the transform, not a convenience. Without`,
    `  it every named path in the generated DTL resolves to empty and nothing`,
    `  errors: the message is delivered, well formed, and carries nothing.`,
    ``,
    `  Import:`,
    `    do ##class(EnsLib.HL7.SchemaXML).Import("<path>", .cat)`,
    `  Then name it in the HL7 Business Service's MessageSchemaCategory setting.`,
  ];

  if (sch.description) out.push(``, `  ${comment(sch.description)}`);

  for (const st of sch.structures) {
    if (st.note) out.push(``, `  ${st.name}: ${comment(st.note)}`);
  }

  out.push(
    `-->`,
    `<Category name="${x(sch.category)}" base="${x(sch.base)}"${
      sch.description ? ` description="${x(sch.description)}"` : ""
    }>`,
  );

  for (const st of sch.structures) {
    out.push(`  <MessageType name="${x(st.name)}" structure="${x(st.name)}"/>`);
  }
  for (const st of sch.structures) {
    out.push(
      `  <MessageStructure name="${x(st.name)}" definition="${x(st.definition)}"/>`,
    );
  }

  out.push(`</Category>`, ``);
  return out.join("\n");
}
